kind = "web"
previewPath = "/"
title = "KIZOTOPUP"
version = "1.0.0"
id = "artifacts/kizotopup"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22918

[services.development]
run = "pnpm --filter @workspace/kizotopup run dev"

[services.env]
PORT = "22918"
